sonar.projectKey=devops-lab-app
sonar.projectName=devops-lab-app

sonar.sources=.
sonar.tests=tests
sonar.exclusions=tests/**,**/__pycache__/**,.pytest_cache/**

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
